consumer_key: CONSUMER_KEY
consumer_secret: CONSUMER_SECRET
feed_url: https://example.com/feed.atom
format: 'Read my post "{{ .Title }}": {{ .Link }}'
token: TOKEN
token_secret: TOKEN_SECRET
username: USERNAME
